name: Sarkari Naukri Job Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

permissions:
  contents: write

jobs:
  check-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run job checker
        run: |
          python job_checker.py
      - name: Test job details extraction
        run: |
          python job_details_test.py
       - name: Test structured job extractor
        run: |
          python extract_job.py
      - name: Save detected jobs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add seen_jobs.json

          git diff --cached --quiet || git commit -m "Update seen jobs"

          git push
